import type { AwardDefinition, AwardImage } from "../types.ts";

const commons = (file: string, sourcePage: string, license: string, author?: string): AwardImage => ({
  src: `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`,
  sourcePage,
  license,
  author,
});

const mn = { country: "MN", countryName: "Монголия / МНР", level: "state" as const, imageStatus: "pending-license-review" as const, issuer: "Монгольская Народная Республика" };
const pl = { country: "PL", countryName: "Польша / ПНР", level: "state" as const, imageStatus: "pending-license-review" as const };
const cs = { country: "CS", countryName: "Чехословакия", level: "state" as const, imageStatus: "pending-license-review" as const };
const ddr = { country: "DDR", countryName: "ГДР", level: "state" as const, imageStatus: "pending-license-review" as const };

export const FOREIGN_AWARDS: AwardDefinition[] = [
  {
    id: "mn-jubilee-30-khalkhin-gol-victory",
    kind: "medal",
    name: "Медаль «30 лет Халхин-Гольской Победы»",
    aliases: [
      "30 лет Халхин-Гольской Победы",
      "30 лет Халхин Гольской Победы",
      "Медаль 30 лет Халхин-Гольской Победы",
      "В память 30-летия победы советских и монгольских войск в районе реки Халхин-Гол",
      "30th Anniversary of the Victory at Khalkhin Gol",
      "Jubilee Medal 30 years of the Victory in Khalkhin-Gol",
    ],
    establishedAt: "1969-06-09",
    tags: ["Монголия", "МНР", "Халхин-Гол", "юбилейная", "военный", "1939", "1969"],
    description: "Юбилейная государственная медаль Монгольской Народной Республики к 30-летию победы на Халхин-Голе.",
    ...mn,
    imageStatus: "verified",
    image: commons(
      "Медаль «30 лет Халхин-Гольской Победы».jpg",
      "https://commons.wikimedia.org/wiki/File:Медаль_«30_лет_Халхин-Гольской_Победы».jpg",
      "PD-Mongolia-exempt",
    ),
  },
  {
    id: "mn-jubilee-40-khalkhin-gol-victory",
    kind: "medal",
    name: "Медаль «40 лет Халхин-Гольской Победы»",
    aliases: ["40 лет Халхин-Гольской Победы", "40 лет Халхин Гольской Победы", "40th Anniversary of the Victory at Khalkhin Gol"],
    establishedAt: "1979-03-19",
    tags: ["Монголия", "МНР", "Халхин-Гол", "юбилейная", "военный", "1939", "1979"],
    description: "Юбилейная государственная медаль МНР к 40-летию победы на Халхин-Голе.",
    ...mn,
  },
  {
    id: "mn-jubilee-30-victory-over-japan",
    kind: "medal",
    name: "Медаль «30 лет Победы над милитаристской Японией»",
    aliases: ["30 лет Победы над Японией МНР", "30 Years of the Victory over militaristic Japan"],
    tags: ["Монголия", "МНР", "Япония", "юбилейная", "военный", "1945"],
    description: "Юбилейная медаль Монгольской Народной Республики.",
    ...mn,
  },
  {
    id: "mn-jubilee-50-peoples-army",
    kind: "medal",
    name: "Медаль «50 лет Монгольской Народной Армии»",
    aliases: ["50 лет МНА", "50 Years of the Mongolian People's Army"],
    tags: ["Монголия", "МНР", "армия", "юбилейная", "военный"],
    description: "Юбилейная медаль Монгольской Народной Республики.",
    ...mn,
  },
  {
    id: "mn-jubilee-50-peoples-revolution",
    kind: "medal",
    name: "Медаль «50 лет Монгольской Народной Революции»",
    aliases: ["50 лет МНР", "50 Years of the Mongolian People's Revolution"],
    tags: ["Монголия", "МНР", "революция", "юбилейная"],
    description: "Юбилейная медаль Монгольской Народной Республики.",
    ...mn,
  },
  {
    id: "mn-medal-friendship",
    kind: "medal",
    name: "Медаль Дружбы (Монголия)",
    aliases: ["Монгольская медаль Дружбы", "Medal of Friendship Mongolia"],
    tags: ["Монголия", "МНР", "дружба", "международная"],
    description: "Государственная награда Монголии/МНР.",
    ...mn,
  },
  {
    id: "mn-order-sukhbaatar",
    kind: "order",
    name: "Орден Сухэ-Батора",
    aliases: ["Орден Сухэ Батора", "Сүхбаатарын одон", "Order of Sukhbaatar"],
    tags: ["Монголия", "МНР", "высшая награда", "военный", "гражданская"],
    description: "Одна из высших государственных наград Монголии.",
    ...mn,
  },
  {
    id: "mn-order-red-banner",
    kind: "order",
    name: "Орден Боевого Красного Знамени (Монголия)",
    aliases: ["Орден Красного Знамени Монголии", "Орден Боевого Красного Знамени МНР"],
    tags: ["Монголия", "МНР", "военный"],
    description: "Военная государственная награда Монгольской Народной Республики.",
    ...mn,
  },
  {
    id: "pl-medal-oder-neisse-baltic",
    kind: "medal",
    name: "Медаль «За Одру, Нису и Балтику»",
    aliases: ["За Одру Нису и Балтику", "За Одер Нейсе и Балтику", "Medal Za Odrę, Nysę i Bałtyk"],
    establishedAt: "1945-10-26",
    tags: ["Польша", "ПНР", "Вторая мировая", "1945", "военный"],
    description: "Польская военная награда за участие в боях на Одре, Нисе и Балтийском побережье.",
    ...pl,
  },
  {
    id: "pl-medal-victory-freedom-1945",
    kind: "medal",
    name: "Медаль «Победы и Свободы 1945»",
    aliases: ["Медаль Победы и Свободы", "Medal Zwycięstwa i Wolności 1945"],
    tags: ["Польша", "ПНР", "Вторая мировая", "1945", "победа"],
    description: "Польская памятная государственная награда, связанная с победой во Второй мировой войне.",
    ...pl,
  },
  {
    id: "pl-medal-brotherhood-arms",
    kind: "medal",
    name: "Медаль «Братство по оружию» (Польша)",
    aliases: ["Польская медаль Братство по оружию", "Братство по оружию ПНР"],
    establishedAt: "1963-10-07",
    tags: ["Польша", "ПНР", "Варшавский договор", "военный", "дружба"],
    description: "Награда Польской Народной Республики за укрепление боевого содружества и военного сотрудничества.",
    ...pl,
  },
  {
    id: "cs-war-cross-1939",
    kind: "cross",
    name: "Чехословацкий Военный крест 1939 года",
    aliases: ["Чехословацкий Военный крест 1939", "Чехословацкий Военный крест 1939-1945", "Czechoslovak War Cross 1939"],
    establishedAt: "1940-12-20",
    tags: ["Чехословакия", "Вторая мировая", "военный", "1939", "1945"],
    description: "Военная награда Чехословакии для участников борьбы за освобождение страны во Второй мировой войне.",
    ...cs,
  },
  {
    id: "ddr-medal-brotherhood-arms",
    kind: "medal",
    name: "Медаль «Братство по оружию» (ГДР)",
    aliases: ["Братство по оружию ГДР", "Medaille der Waffenbrüderschaft"],
    establishedAt: "1966-02-17",
    tags: ["ГДР", "Варшавский договор", "военный", "дружба"],
    degrees: [
      { id: "1", label: "Золотая", aliases: ["в золоте", "золотая"] },
      { id: "2", label: "Серебряная", aliases: ["в серебре", "серебряная"] },
      { id: "3", label: "Бронзовая", aliases: ["бронзовая"] },
    ],
    description: "Государственная награда ГДР за укрепление дружбы и братского союза между армиями социалистических государств.",
    ...ddr,
  },
];
