-- Runtime service tables. Every archive-owned row is protected by forced RLS.
-- Run as the migration role, never automatically from a web request.

CREATE TABLE IF NOT EXISTS share_links (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
  id TEXT NOT NULL,
  token_hash TEXT  NOT NULL,
  title TEXT NOT NULL,
  anchor_id TEXT NOT NULL,
  person_ids jsonb NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_name TEXT NOT NULL,
  revoked_at TEXT
,
  PRIMARY KEY(archive_id,id),
  UNIQUE(archive_id,token_hash));

CREATE TABLE IF NOT EXISTS share_link_activity (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true),
  share_id text NOT NULL,
  last_visited_at text NOT NULL,
  PRIMARY KEY (archive_id, share_id),
  FOREIGN KEY (archive_id, share_id)
    REFERENCES share_links(archive_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS geocode_cache (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  data TEXT NOT NULL,
  saved_at bigint NOT NULL
,
  PRIMARY KEY(archive_id,query));

CREATE TABLE IF NOT EXISTS migrations (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
  id TEXT NOT NULL
,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS face_descriptors (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        person_id TEXT NOT NULL,
        data jsonb NOT NULL,
        created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
      , source_tag_id TEXT, created_by TEXT, source_photo_id TEXT, model TEXT NOT NULL DEFAULT 'face-api-1.7.15',
  PRIMARY KEY(archive_id,id),
  FOREIGN KEY(archive_id,person_id) REFERENCES people(archive_id,id) ON DELETE CASCADE,
  FOREIGN KEY(archive_id,source_tag_id) REFERENCES photo_tags(archive_id,id) ON DELETE CASCADE,
  FOREIGN KEY(archive_id,source_photo_id) REFERENCES photos(archive_id,id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS mcp_tokens (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        token_hash TEXT  NOT NULL,
        token_hint TEXT NOT NULL,
        name TEXT NOT NULL,
        scopes jsonb NOT NULL,
        created_at TEXT NOT NULL,
        expires_at bigint,
        created_by TEXT NOT NULL,
        revoked_at TEXT,
        last_used_at bigint
      , rate_limit_per_minute bigint NOT NULL DEFAULT 60
          CHECK(rate_limit_per_minute BETWEEN 0 AND 600), bound_user_id TEXT,
  PRIMARY KEY(archive_id,id),
  UNIQUE(archive_id,token_hash),
  FOREIGN KEY(archive_id,bound_user_id) REFERENCES archive_memberships(archive_id,user_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS ai_settings (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id bigint NOT NULL CHECK(id=1),
        enabled bigint NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),
        model TEXT NOT NULL DEFAULT ''
      , requests_per_minute bigint NOT NULL DEFAULT 6
          CHECK(requests_per_minute BETWEEN 0 AND 120), daily_requests bigint NOT NULL DEFAULT 100
          CHECK(daily_requests BETWEEN 0 AND 100000), daily_tokens bigint NOT NULL DEFAULT 250000
          CHECK(daily_tokens BETWEEN 0 AND 1000000000), api_key_ciphertext TEXT NOT NULL DEFAULT '', folder_id TEXT NOT NULL DEFAULT '', compaction_enabled bigint NOT NULL DEFAULT 1 CHECK(compaction_enabled IN (0,1)), compact_threshold_tokens bigint NOT NULL DEFAULT 32000 CHECK(compact_threshold_tokens BETWEEN 1000 AND 1000000), automatic_truncation bigint NOT NULL DEFAULT 1 CHECK(automatic_truncation IN (0,1)), max_tool_iterations bigint NOT NULL DEFAULT 8 CHECK(max_tool_iterations BETWEEN 1 AND 20), web_search_enabled bigint CHECK(web_search_enabled IS NULL OR web_search_enabled IN (0,1)),
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS ai_usage (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        at TEXT NOT NULL,
        started_ms bigint NOT NULL,
        user_id TEXT NOT NULL,
        model TEXT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('ok','error')),
        provider_calls bigint NOT NULL,
        input_tokens bigint NOT NULL,
        output_tokens bigint NOT NULL,
        total_tokens bigint NOT NULL,
        latency_ms bigint NOT NULL
      , cached_input_tokens bigint NOT NULL DEFAULT 0,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS mcp_usage (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        at TEXT NOT NULL,
        started_ms bigint NOT NULL,
        token_id TEXT NOT NULL,
        method TEXT NOT NULL,
        tool_name TEXT,
        status TEXT NOT NULL CHECK(status IN ('ok','error')),
        latency_ms bigint NOT NULL
      ,
  PRIMARY KEY(archive_id,id),
  FOREIGN KEY(archive_id,token_id) REFERENCES mcp_tokens(archive_id,id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS research_suggestions (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        kind TEXT NOT NULL CHECK(kind IN ('person_create','person_update','source','relation')),
        status TEXT NOT NULL CHECK(status IN ('pending','accepted','rejected')),
        person_id TEXT NOT NULL,
        payload jsonb NOT NULL,
        reason TEXT NOT NULL,
        evidence jsonb NOT NULL,
        base_revision bigint NOT NULL,
        created_at TEXT NOT NULL,
        created_by TEXT NOT NULL,
        reviewed_at TEXT,
        reviewed_by TEXT
      ,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS ai_usage_models (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        usage_id bigint NOT NULL,
        model TEXT NOT NULL,
        provider_calls bigint NOT NULL,
        input_tokens bigint NOT NULL,
        output_tokens bigint NOT NULL,
        total_tokens bigint NOT NULL,
        PRIMARY KEY(archive_id,usage_id,model)
      ,
  FOREIGN KEY(archive_id,usage_id) REFERENCES ai_usage(archive_id,id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS ai_chats (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        access_scope TEXT NOT NULL,
        yandex_conversation_id TEXT,
        session_state jsonb NOT NULL DEFAULT '{"schemaVersion":1,"activePersonIds":[]}',
        created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
        updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
        busy_token TEXT,
        busy_until bigint
      ,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS ai_chat_messages (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        chat_id TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('user','assistant')),
        content TEXT NOT NULL,
        data jsonb NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
      ,
  PRIMARY KEY(archive_id,id),
  FOREIGN KEY(archive_id,chat_id) REFERENCES ai_chats(archive_id,id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS research_categories (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        name TEXT NOT NULL,
        sort_order bigint NOT NULL
      ,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS research_resources (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        category_id TEXT NOT NULL,
        name TEXT NOT NULL,
        url TEXT NOT NULL,
        description TEXT NOT NULL,
        sort_order bigint NOT NULL, ai_search jsonb,
        UNIQUE(archive_id,category_id,url)
      ,
  PRIMARY KEY(archive_id,id),
  FOREIGN KEY(archive_id,category_id) REFERENCES research_categories(archive_id,id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS workflow_stages (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
          token TEXT NOT NULL,
          kind TEXT NOT NULL CHECK(kind IN ('gedcom','restore')),
          actor_id TEXT NOT NULL,
          revision bigint NOT NULL,
          expires_at bigint NOT NULL,
          data jsonb NOT NULL,
          directory TEXT,
          UNIQUE(archive_id,kind, actor_id)
        ,
  PRIMARY KEY(archive_id,token));

CREATE TABLE IF NOT EXISTS document_upload_requests (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
      id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      started_ms bigint NOT NULL,
      expires_ms bigint NOT NULL,
      reserved_bytes bigint NOT NULL CHECK(reserved_bytes>=0)
    ,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS backup_settings (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,id bigint NOT NULL CHECK(id=1), data jsonb NOT NULL, next_run bigint NOT NULL,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS backup_catalog (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,id TEXT NOT NULL, name TEXT NOT NULL , created_at TEXT NOT NULL, data jsonb NOT NULL,
  PRIMARY KEY(archive_id,id),
  UNIQUE(archive_id,name));

CREATE TABLE IF NOT EXISTS backup_job (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,id bigint NOT NULL CHECK(id=1), owner TEXT NOT NULL, actor_id TEXT NOT NULL, lease_until bigint NOT NULL, data jsonb NOT NULL,
  PRIMARY KEY(archive_id,id));

CREATE TABLE IF NOT EXISTS media_upload_grants (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
        url TEXT NOT NULL,
        user_id TEXT NOT NULL,
        expires_ms bigint NOT NULL
      ,
  PRIMARY KEY(archive_id,url));

CREATE TABLE IF NOT EXISTS user_tree_preferences (
  archive_id text NOT NULL DEFAULT current_setting('drevo.archive_id', true) REFERENCES archives(id) ON DELETE CASCADE,
          user_id TEXT NOT NULL,
          reverse_timeline bigint NOT NULL CHECK(reverse_timeline IN (0,1)),
          card_variant TEXT NOT NULL CHECK(card_variant IN ('classic','portrait'))
        , color_scheme TEXT NOT NULL DEFAULT 'warm' CHECK(color_scheme IN ('warm','white')),
  PRIMARY KEY(archive_id,user_id));

ALTER TABLE people ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_people_ordinal;
ALTER TABLE people ALTER COLUMN ordinal SET DEFAULT nextval('runtime_people_ordinal');
SELECT setval('runtime_people_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM people),0)+1,1), false);

ALTER TABLE photos ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_photos_ordinal;
ALTER TABLE photos ALTER COLUMN ordinal SET DEFAULT nextval('runtime_photos_ordinal');
SELECT setval('runtime_photos_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM photos),0)+1,1), false);

ALTER TABLE relations ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_relations_ordinal;
ALTER TABLE relations ALTER COLUMN ordinal SET DEFAULT nextval('runtime_relations_ordinal');
SELECT setval('runtime_relations_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM relations),0)+1,1), false);

ALTER TABLE photo_tags ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_photo_tags_ordinal;
ALTER TABLE photo_tags ALTER COLUMN ordinal SET DEFAULT nextval('runtime_photo_tags_ordinal');
SELECT setval('runtime_photo_tags_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM photo_tags),0)+1,1), false);

ALTER TABLE documents ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_documents_ordinal;
ALTER TABLE documents ALTER COLUMN ordinal SET DEFAULT nextval('runtime_documents_ordinal');
SELECT setval('runtime_documents_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM documents),0)+1,1), false);

ALTER TABLE document_people ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_document_people_ordinal;
ALTER TABLE document_people ALTER COLUMN ordinal SET DEFAULT nextval('runtime_document_people_ordinal');
SELECT setval('runtime_document_people_ordinal', GREATEST(COALESCE((SELECT max(ordinal) FROM document_people),0)+1,1), false);
ALTER TABLE history ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE person_comments ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE archive_audit_entries ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE archive_audit_people ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE archive_memberships ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE archive_access_settings ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
ALTER TABLE archive_tree_settings ALTER COLUMN archive_id SET DEFAULT current_setting('drevo.archive_id', true);
CREATE SEQUENCE IF NOT EXISTS runtime_person_comments_id;
ALTER TABLE person_comments ALTER COLUMN id SET DEFAULT nextval('runtime_person_comments_id');
SELECT setval('runtime_person_comments_id', GREATEST(COALESCE((SELECT max(id) FROM person_comments),0)+1,1), false);
CREATE SEQUENCE IF NOT EXISTS runtime_archive_audit_entries_id;
ALTER TABLE archive_audit_entries ALTER COLUMN id SET DEFAULT nextval('runtime_archive_audit_entries_id');
SELECT setval('runtime_archive_audit_entries_id', GREATEST(COALESCE((SELECT max(id) FROM archive_audit_entries),0)+1,1), false);
ALTER TABLE history ALTER COLUMN saved_at SET DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
ALTER TABLE accounts ALTER COLUMN created_at SET DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
CREATE UNIQUE INDEX IF NOT EXISTS research_categories_name ON research_categories(archive_id,lower(name));
CREATE INDEX IF NOT EXISTS face_descriptors_person ON face_descriptors(archive_id,person_id);
CREATE INDEX IF NOT EXISTS mcp_tokens_active ON mcp_tokens(archive_id,revoked_at,expires_at);
CREATE INDEX IF NOT EXISTS ai_usage_user_started
        ON ai_usage(archive_id,user_id,started_ms DESC);
CREATE INDEX IF NOT EXISTS ai_usage_started
        ON ai_usage(archive_id,started_ms DESC);
CREATE INDEX IF NOT EXISTS mcp_usage_token_started
        ON mcp_usage(archive_id,token_id,started_ms DESC);
CREATE INDEX IF NOT EXISTS mcp_usage_started
        ON mcp_usage(archive_id,started_ms DESC);
CREATE INDEX IF NOT EXISTS mcp_tokens_bound_user
          ON mcp_tokens(archive_id,bound_user_id);
CREATE INDEX IF NOT EXISTS research_suggestions_status
        ON research_suggestions(archive_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS research_suggestions_creator
        ON research_suggestions(archive_id,created_by,status);
CREATE INDEX IF NOT EXISTS face_descriptors_source_tag
          ON face_descriptors(archive_id,source_tag_id);
CREATE INDEX IF NOT EXISTS ai_usage_models_model
        ON ai_usage_models(archive_id,model,usage_id);
CREATE INDEX IF NOT EXISTS ai_chats_user_updated ON ai_chats(archive_id,user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS ai_chat_messages_chat_id ON ai_chat_messages(archive_id,chat_id,id);
CREATE INDEX IF NOT EXISTS research_resources_category_order
        ON research_resources(archive_id,category_id,sort_order,id);
CREATE INDEX IF NOT EXISTS workflow_stages_expiry ON workflow_stages(archive_id,expires_at);
CREATE INDEX IF NOT EXISTS document_upload_requests_user ON document_upload_requests(archive_id,user_id,started_ms);
CREATE INDEX IF NOT EXISTS backup_catalog_date ON backup_catalog(archive_id,created_at DESC);
CREATE INDEX IF NOT EXISTS media_upload_grants_expiry ON media_upload_grants(archive_id,expires_ms);

ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE people FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON people;
CREATE POLICY archive_scope ON people USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE photos FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON photos;
CREATE POLICY archive_scope ON photos USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE relations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON relations;
CREATE POLICY archive_scope ON relations USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE photo_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_tags FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON photo_tags;
CREATE POLICY archive_scope ON photo_tags USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON documents;
CREATE POLICY archive_scope ON documents USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE document_people ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_people FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON document_people;
CREATE POLICY archive_scope ON document_people USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE history ENABLE ROW LEVEL SECURITY;
ALTER TABLE history FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON history;
CREATE POLICY archive_scope ON history USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE person_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE person_comments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON person_comments;
CREATE POLICY archive_scope ON person_comments USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_audit_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_audit_entries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_audit_entries;
CREATE POLICY archive_scope ON archive_audit_entries USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_audit_people ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_audit_people FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_audit_people;
CREATE POLICY archive_scope ON archive_audit_people USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_memberships FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_memberships;
CREATE POLICY archive_scope ON archive_memberships USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_owners FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_owners;
CREATE POLICY archive_scope ON archive_owners USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_access_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_access_settings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_access_settings;
CREATE POLICY archive_scope ON archive_access_settings USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archive_tree_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_tree_settings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archive_tree_settings;
CREATE POLICY archive_scope ON archive_tree_settings USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE share_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE share_links FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON share_links;
CREATE POLICY archive_scope ON share_links USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE share_link_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE share_link_activity FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON share_link_activity;
CREATE POLICY archive_scope ON share_link_activity USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE geocode_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE geocode_cache FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON geocode_cache;
CREATE POLICY archive_scope ON geocode_cache USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE migrations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON migrations;
CREATE POLICY archive_scope ON migrations USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE face_descriptors ENABLE ROW LEVEL SECURITY;
ALTER TABLE face_descriptors FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON face_descriptors;
CREATE POLICY archive_scope ON face_descriptors USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE mcp_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_tokens FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON mcp_tokens;
CREATE POLICY archive_scope ON mcp_tokens USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE ai_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_settings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON ai_settings;
CREATE POLICY archive_scope ON ai_settings USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON ai_usage;
CREATE POLICY archive_scope ON ai_usage USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE mcp_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp_usage FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON mcp_usage;
CREATE POLICY archive_scope ON mcp_usage USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE research_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_suggestions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON research_suggestions;
CREATE POLICY archive_scope ON research_suggestions USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE ai_usage_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage_models FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON ai_usage_models;
CREATE POLICY archive_scope ON ai_usage_models USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE ai_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_chats FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON ai_chats;
CREATE POLICY archive_scope ON ai_chats USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE ai_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_chat_messages FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON ai_chat_messages;
CREATE POLICY archive_scope ON ai_chat_messages USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE research_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_categories FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON research_categories;
CREATE POLICY archive_scope ON research_categories USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE research_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_resources FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON research_resources;
CREATE POLICY archive_scope ON research_resources USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE workflow_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_stages FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON workflow_stages;
CREATE POLICY archive_scope ON workflow_stages USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE document_upload_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_upload_requests FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON document_upload_requests;
CREATE POLICY archive_scope ON document_upload_requests USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE backup_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_settings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON backup_settings;
CREATE POLICY archive_scope ON backup_settings USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE backup_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_catalog FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON backup_catalog;
CREATE POLICY archive_scope ON backup_catalog USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE backup_job ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_job FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON backup_job;
CREATE POLICY archive_scope ON backup_job USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE media_upload_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_upload_grants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON media_upload_grants;
CREATE POLICY archive_scope ON media_upload_grants USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE user_tree_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_tree_preferences FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON user_tree_preferences;
CREATE POLICY archive_scope ON user_tree_preferences USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));

ALTER TABLE archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE archives FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON archives;
CREATE POLICY archive_scope ON archives USING (id=current_setting('drevo.archive_id', true)) WITH CHECK (id=current_setting('drevo.archive_id', true));

-- Read projections retain the application's account contract without duplicating it.
ALTER TABLE service_snapshot_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_snapshot_tables FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON service_snapshot_tables;
CREATE POLICY archive_scope ON service_snapshot_tables USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));
ALTER TABLE service_snapshot_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_snapshot_rows FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS archive_scope ON service_snapshot_rows;
CREATE POLICY archive_scope ON service_snapshot_rows USING (archive_id=current_setting('drevo.archive_id', true)) WITH CHECK (archive_id=current_setting('drevo.archive_id', true));
CREATE OR REPLACE VIEW runtime_users WITH (security_invoker=true) AS
 SELECT a.id,a.name,a.created_at,a.last_visit_at,m.role,m.approved::integer AS approved,m.person_id,m.tree_access
 FROM accounts a JOIN archive_memberships m ON m.user_id=a.id;
CREATE OR REPLACE VIEW runtime_access_settings WITH (security_invoker=true) AS
 SELECT 1 AS id,public_tree::integer AS public_tree,public_albums::integer AS public_albums FROM archive_access_settings;
CREATE OR REPLACE VIEW runtime_tree_settings WITH (security_invoker=true) AS
 SELECT 1 AS id,reverse_timeline::integer AS reverse_timeline FROM archive_tree_settings;
ALTER TABLE share_links ADD COLUMN IF NOT EXISTS ordinal bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE face_descriptors ADD COLUMN IF NOT EXISTS ordinal bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS share_links_ordinal ON share_links(archive_id,ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS face_descriptors_ordinal ON face_descriptors(archive_id,ordinal);
CREATE INDEX IF NOT EXISTS photos_url ON photos(archive_id,(data->>'url'));
CREATE INDEX IF NOT EXISTS people_photo ON people(archive_id,(data->>'photo'));
CREATE INDEX IF NOT EXISTS photo_tags_photo ON photo_tags(archive_id,photo_id);
CREATE INDEX IF NOT EXISTS documents_created ON documents(archive_id,created_at DESC,id DESC);

CREATE OR REPLACE FUNCTION runtime_tag_changed() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 UPDATE face_descriptors SET person_id=NEW.person_id,source_photo_id=NEW.photo_id
 WHERE archive_id=NEW.archive_id AND source_tag_id=NEW.id;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS runtime_tag_changed ON photo_tags;
CREATE TRIGGER runtime_tag_changed AFTER UPDATE OF person_id,photo_id ON photo_tags
 FOR EACH ROW EXECUTE FUNCTION runtime_tag_changed();
CREATE OR REPLACE FUNCTION runtime_member_deleted() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 DELETE FROM ai_chats WHERE archive_id=OLD.archive_id AND user_id=OLD.user_id;
 DELETE FROM account_sessions WHERE user_id=OLD.user_id;
 RETURN OLD;
END $$;
DROP TRIGGER IF EXISTS runtime_member_deleted ON archive_memberships;
CREATE TRIGGER runtime_member_deleted AFTER DELETE ON archive_memberships
 FOR EACH ROW EXECUTE FUNCTION runtime_member_deleted();
