ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_type text NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_date text NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS place text NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS provenance text NOT NULL DEFAULT '';
